### PR TITLE
Integrate and display detailed movie information on the movie page

### PR DESCRIPTION
**Pull request by viss5vuus98**

### CODE REVIEW

**Review by muchuanhung — APPROVED** [review]
ok

**Review by muchuanhung — CHANGES_REQUESTED** [review]
ci eslint 有問題
vercel沒過

**Comment by viss5vuus98** [comment]
> ci eslint 有問題 vercel沒過

已修復 感謝~

**Review by wen1011 — APPROVED** [review]
Ok thank you

**Review by muchuanhung — APPROVED** [review]
ok

**Pull request merged**
